### ISSUE TITLE
Progress bar keeps rotating after unsucessfull login attempt

### ISSUE THREAD

**Issue by HritikrBelani** [kunalpat25/WCEVISITCOVID19#3]
Type a wrong email id or password and try to authenticate in Mainactivity.java , it will show that credentials are wrong and will tell you to authenticate with correct email id and password , while all this happening the progress bar still rotates which looks irritating and not userfriendly.

**Comment by kunalpat25** [comment]
Would you like to work on it?

**Comment by HritikrBelani** [comment]
Yes i am ok with it :) .
